# Generated by Django 4.2.5 on 2023-10-05 06:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(default='', max_length=255)),
                ('last_name', models.CharField(default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'User',
            },
        ),
        migrations.CreateModel(
            name='Toggles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Toggles', max_length=100)),
                ('stop_pipedrive_webhooks', models.BooleanField(default=False)),
                ('stop_stripe_webhooks', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('address', models.CharField(default='', max_length=100)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OngoingSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('action', models.CharField(default='', max_length=100)),
                ('key_or_id', models.CharField(default='', max_length=100)),
                ('stop_pipedrive_webhook', models.BooleanField(default=False)),
                ('has_recieved_pipedrive_webhook', models.BooleanField(default=False)),
                ('stop_stripe_webhook', models.BooleanField(default=False)),
                ('has_recieved_stripe_webhook', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='Joe', max_length=100)),
                ('last_name', models.CharField(default='Dierte', max_length=100)),
                ('role', models.CharField(default='sales', max_length=100)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_picture/')),
                ('bio', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('linkedin', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('github', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('display_on_website', models.BooleanField(blank=True, default=False, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=100)),
                ('last_name', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('phone', models.CharField(blank=True, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profilte_picture/')),
                ('status', models.CharField(choices=[('lead', 'Lead'), ('customer', 'Customer')], default='lead', max_length=100)),
                ('onboarding_date', models.DateTimeField(blank=True, null=True)),
                ('monday_id', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('pipedrive_id', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('pipedrive_user_id', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('piprdrive_api_url', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('stripe_customer_id', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('stripe_account_id', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('original_sync_from', models.CharField(blank=True, default='roseware', max_length=100, null=True)),
                ('last_synced_from', models.CharField(blank=True, default='roseware', max_length=100, null=True)),
                ('has_synced_pipedrive', models.BooleanField(default=False)),
                ('has_synced_stripe', models.BooleanField(default=False)),
                ('beta_feature_flag', models.BooleanField(default=True)),
                ('PIPEDRIVE_PERSON_STRIPE_URL_KEY', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('PIPEDRIVE_PRODUCT_STRIPE_URL_KEY', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('PIPEDRIVE_DEAL_STRIPE_URL_KEY', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('PIPEDRIVE_DEAL_TYPE_FIELD', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('PIPEDRIVE_DEAL_SUBSCRIPTION_SELECTOR', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('PIPEDRIVE_DEAL_PAYOUT_SELECTOR', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('PIPEDRIVE_DEAL_PROCESSING_FIELD', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('PIPEDRIVE_DEAL_INVOICE_SELECTOR', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('PIPEDRIVE_DEAL_PROCESS_NOW_SELECTOR', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_owner', to=settings.AUTH_USER_MODEL)),
                ('rep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.employee')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
