# Generated by Django 4.1.2 on 2022-11-02 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="first_name",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="customer",
            name="last_name",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="marketer",
            name="first_name",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="marketer",
            name="last_name",
            field=models.TextField(default=""),
        ),
    ]
