# Generated by Django 4.1.7 on 2023-02-17 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customer_first_name_customer_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='ayrshare_key',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='customer',
            name='ayrshare_ref_id',
            field=models.TextField(default=''),
        ),
    ]
