# Generated by Django 4.2.4 on 2023-10-22 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_ongoingsync_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ongoingsync',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
