# Generated by Django 4.1.7 on 2023-03-04 19:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0005_rename_marketer_customer_rep"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Marketer",
            new_name="Employee",
        ),
    ]
