# Generated by Django 4.1.7 on 2023-03-11 01:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_rename_marketer_employee"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="monday_id",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
    ]
