# Generated by Django 4.1.7 on 2023-03-12 21:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_customer_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="pipedrive_id",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
    ]
