# Generated by Django 4.1.7 on 2023-03-30 01:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0009_customer_pipedrive_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="stripe_customer_id",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
    ]
