# Generated by Django 4.2 on 2023-04-08 21:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0012_ongoingsync_action_ongoingsync_customer"),
    ]

    operations = [
        migrations.CreateModel(
            name="Toggles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stop_pipedrive_webhooks", models.BooleanField(default=False)),
                ("stop_stripe_webhooks", models.BooleanField(default=False)),
            ],
        ),
    ]
