# Generated by Django 4.2 on 2023-04-11 00:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0014_toggles_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="ongoingsync",
            name="key_or_id",
            field=models.CharField(default="", max_length=100),
        ),
    ]
