# Generated by Django 4.2 on 2023-04-12 00:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0015_ongoingsync_key_or_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="ongoingsync",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
