# Generated by Django 4.2 on 2023-04-12 01:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0016_ongoingsync_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ongoingsync",
            name="customer",
        ),
    ]
