# Generated by Django 4.2 on 2023-04-15 04:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0017_remove_ongoingsync_customer"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="last_synced_from",
            field=models.CharField(
                blank=True, default="roseware", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="original_sync_from",
            field=models.CharField(
                blank=True, default="roseware", max_length=100, null=True
            ),
        ),
    ]
