# Generated by Django 4.2.1 on 2023-06-16 00:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marketing_manager", "0006_day"),
        ("accounts", "0018_customer_last_synced_from_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="selected_days",
            field=models.ManyToManyField(blank=True, to="marketing_manager.day"),
        ),
    ]
