# Generated by Django 4.2.1 on 2023-06-16 00:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0019_customer_selected_days"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="selected_days",
        ),
    ]
