# Generated by Django 4.2.3 on 2023-07-22 04:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0020_remove_customer_selected_days"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="pipedrive_user_id",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
    ]
