# Generated by Django 4.2.3 on 2023-07-23 00:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0022_customer_invoice_approval_option_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customer",
            old_name="subscription_option_id",
            new_name="PIPEDRIVE_DEAL_PROCESS_NOW_SELECTOR",
        ),
        migrations.RenameField(
            model_name="customer",
            old_name="invoice_approval_option_id",
            new_name="PIPEDRIVE_DEAL_STRIPE_URL_KEY",
        ),
        migrations.RenameField(
            model_name="customer",
            old_name="one_time_option_id",
            new_name="PIPEDRIVE_DEAL_SUBSCRIPTION_SELECTOR",
        ),
        migrations.RenameField(
            model_name="customer",
            old_name="process_immediately_option_id",
            new_name="PIPEDRIVE_DEAL_TYPE_FIELD",
        ),
        migrations.AddField(
            model_name="customer",
            name="PIPEDRIVE_DEAL_INVOICE_SELECTOR",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="PIPEDRIVE_DEAL_PAYOUT_SELECTOR",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="PIPEDRIVE_DEAL_PROCESSING_FIELD",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="PIPEDRIVE_PERSON_STRIPE_URL_KEY",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="PIPEDRIVE_PRODUCT_STRIPE_URL_KEY",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
    ]
