# Generated by Django 4.2.3 on 2023-07-23 19:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "accounts",
            "0023_rename_subscription_option_id_customer_pipedrive_deal_process_now_selector_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="piprdrive_api_url",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
    ]
