# Generated by Django 4.2.3 on 2023-07-29 23:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0024_customer_piprdrive_api_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="has_synced_pipedrive",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customer",
            name="has_synced_stripe",
            field=models.BooleanField(default=False),
        ),
    ]
