# Generated by Django 4.2.3 on 2023-08-05 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0027_ongoingsync_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="bio",
            field=models.CharField(default="", max_length=1000),
        ),
        migrations.AddField(
            model_name="employee",
            name="display_on_website",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="employee",
            name="github",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="employee",
            name="linkedin",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="employee",
            name="role",
            field=models.CharField(default="sales", max_length=100),
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=100)),
                ("address", models.CharField(default="", max_length=100)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organization_owner",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
