# Generated by Django 4.2.3 on 2023-08-05 18:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0028_employee_bio_employee_display_on_website_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="phone",
            field=models.CharField(blank=True, null=True),
        ),
    ]
