# Generated by Django 4.2.3 on 2023-08-05 21:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0029_alter_customer_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="profilte_picture"
            ),
        ),
    ]
