# Generated by Django 4.2.3 on 2023-08-08 03:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0030_customer_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="beta_feature_flag",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="customer",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="profilte_picture/"
            ),
        ),
    ]
