# Generated by Django 4.2.4 on 2023-08-25 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_customer_beta_feature_flag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='bio',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='display_on_website',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='github',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='linkedin',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
