# Generated by Django 4.2.4 on 2023-08-26 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_blogarticle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogArticle',
        ),
    ]
