# Generated by Django 4.2.4 on 2023-09-02 17:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0035_employee_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="stripe_account_id",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
    ]
