# Generated by Django 4.2.4 on 2023-09-04 00:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0037_alter_customer_beta_feature_flag_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ongoingsync",
            name="owner",
        ),
        migrations.AddField(
            model_name="ongoingsync",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
