version: '3.8'
services:
  postgres:
    container_name: postgres
    env_file:
      - .env
    image: postgres:latest
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    restart: always
    volumes:
      - db:/var/lib/postgresql/data/

  pgadmin:
    env_file:
      - .env
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_MAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PW}
    ports:
      - "5050:80"
    restart: always

  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672

  # celery:


  web:
    env_file:
      - .env
    build: .
    command: "./start.sh"
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - postgres
      - rabbitmq
      # - celery

volumes:
    db: