# Generated by Django 4.2.1 on 2023-06-11 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MarketingSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.DateField()),
                ("topic", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="WeeklyTopic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week_start_date", models.DateField()),
                ("topic", models.CharField(max_length=200)),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weekly_topics",
                        to="marketing_manager.marketingschedule",
                    ),
                ),
            ],
            options={
                "unique_together": {("schedule", "week_start_date")},
            },
        ),
    ]
