# Generated by Django 4.2.1 on 2023-06-11 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0018_customer_last_synced_from_and_more"),
        ("marketing_manager", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="marketingschedule",
            name="customer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.customer",
            ),
        ),
        migrations.AddField(
            model_name="marketingschedule",
            name="title",
            field=models.CharField(default="test", max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="weeklytopic",
            name="schedule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="marketing_schedule",
                to="marketing_manager.marketingschedule",
            ),
        ),
        migrations.CreateModel(
            name="DailyContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("daily_topic", models.CharField(max_length=200)),
                ("title", models.CharField(max_length=200)),
                (
                    "content_type",
                    models.CharField(
                        choices=[("social_media", "Social Media")], max_length=100
                    ),
                ),
                (
                    "weekly_topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weekly_topic",
                        to="marketing_manager.weeklytopic",
                    ),
                ),
            ],
        ),
    ]
