# Generated by Django 4.2.1 on 2023-06-12 02:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "marketing_manager",
            "0002_marketingschedule_customer_marketingschedule_title_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="marketingschedule",
            old_name="month",
            new_name="start_date",
        ),
        migrations.AddField(
            model_name="dailycontent",
            name="scheduled_date",
            field=models.DateField(default=datetime.date(2023, 6, 12)),
            preserve_default=False,
        ),
    ]
