# Generated by Django 4.2.1 on 2023-06-12 03:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "marketing_manager",
            "0003_rename_month_marketingschedule_start_date_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailycontent",
            name="daily_topic",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="dailycontent",
            name="title",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="marketingschedule",
            name="start_date",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name="marketingschedule",
            name="title",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="marketingschedule",
            name="topic",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="weeklytopic",
            name="topic",
            field=models.CharField(max_length=100),
        ),
    ]
