# Generated by Django 4.2.1 on 2023-06-13 00:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("marketing_manager", "0004_alter_dailycontent_daily_topic_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="weeklytopic",
            name="title",
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
