# Generated by Django 4.2.1 on 2023-06-16 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0020_remove_customer_selected_days"),
        ("marketing_manager", "0007_day_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="day",
            name="customer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.customer",
            ),
        ),
    ]
