# Generated by Django 4.2.1 on 2023-06-16 01:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marketing_manager", "0008_day_customer"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailycontent",
            name="index",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="weeklytopic",
            name="index",
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
