# Generated by Django 4.2.1 on 2023-06-24 03:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marketing_manager", "0010_socialpost_customerselectedplatform"),
    ]

    operations = [
        migrations.AddField(
            model_name="socialpost",
            name="caption",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="socialpost",
            name="date_posted",
            field=models.DateField(
                default=datetime.datetime(2023, 6, 24, 3, 44, 46, 740286)
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="socialpost",
            name="platform",
            field=models.CharField(default="facebook", max_length=100),
            preserve_default=False,
        ),
    ]
