# Generated by Django 4.2.2 on 2023-06-24 07:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "marketing_manager",
            "0011_socialpost_caption_socialpost_date_posted_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="socialpost",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="social_media_posts"
            ),
        ),
    ]
