# Generated by Django 4.2.2 on 2023-06-24 08:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marketing_manager", "0012_socialpost_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="socialpost",
            name="date_posted",
            field=models.DateField(blank=True, null=True),
        ),
    ]
