# Generated by Django 4.2.4 on 2023-08-26 02:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketing_manager', '0015_blogarticle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogarticle',
            name='auther',
        ),
        migrations.AddField(
            model_name='blogarticle',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL),
        ),
    ]
