# Generated by Django 4.2.5 on 2023-10-05 06:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('package_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=255, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customer')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription_owner', to=settings.AUTH_USER_MODEL)),
                ('package_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='package_manager.packageplan')),
            ],
        ),
        migrations.CreateModel(
            name='StripePaymentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(blank=True, max_length=255, null=True)),
                ('expiry_month', models.CharField(blank=True, max_length=255, null=True)),
                ('expiry_year', models.CharField(blank=True, max_length=255, null=True)),
                ('cvc', models.CharField(blank=True, max_length=255, null=True)),
                ('card_holder_name', models.CharField(blank=True, max_length=255, null=True)),
                ('card_holder_email', models.CharField(blank=True, max_length=255, null=True)),
                ('card_holder_phone', models.CharField(blank=True, max_length=255, null=True)),
                ('card_holder_address', models.CharField(blank=True, max_length=255, null=True)),
                ('card_holder_city', models.CharField(blank=True, max_length=255, null=True)),
                ('card_holder_state', models.CharField(blank=True, max_length=255, null=True)),
                ('card_holder_zip', models.CharField(blank=True, max_length=255, null=True)),
                ('card_holder_country', models.CharField(blank=True, max_length=255, null=True)),
                ('stripe_card_id', models.CharField(blank=True, max_length=255, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customer')),
            ],
        ),
    ]
