# Generated by Django 4.1.7 on 2023-03-30 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "package_manager",
            "0024_rename_stripe_id_servicepackagetemplate_stripe_price_id_and_more",
        ),
        ("accounts", "0010_customer_stripe_customer_id"),
        ("stripe", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PaymentDetails",
            new_name="StripePaymentDetails",
        ),
        migrations.CreateModel(
            name="StripeSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stripe_subscription_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.customer",
                    ),
                ),
                (
                    "package_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="package_manager.packageplan",
                    ),
                ),
            ],
        ),
    ]
