# Generated by Django 4.1.7 on 2023-03-30 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "package_manager",
            "0024_rename_stripe_id_servicepackagetemplate_stripe_price_id_and_more",
        ),
        ("stripe", "0002_rename_paymentdetails_stripepaymentdetails_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="stripepaymentdetails",
            old_name="expiry_date",
            new_name="expiry_month",
        ),
        migrations.RenameField(
            model_name="stripepaymentdetails",
            old_name="type",
            new_name="expiry_year",
        ),
        migrations.AddField(
            model_name="stripesubscription",
            name="payment_details",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="stripe.stripepaymentdetails",
            ),
        ),
        migrations.AlterField(
            model_name="stripesubscription",
            name="package_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="package_manager.packageplan",
            ),
        ),
    ]
