# Generated by Django 4.1.7 on 2023-03-30 03:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "stripe",
            "0003_rename_expiry_date_stripepaymentdetails_expiry_month_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="stripepaymentdetails",
            old_name="cvv",
            new_name="cvc",
        ),
    ]
