# Generated by Django 4.1.7 on 2023-03-31 01:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stripe", "0004_rename_cvv_stripepaymentdetails_cvc"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stripepaymentdetails",
            name="card_holder_address",
        ),
        migrations.RemoveField(
            model_name="stripepaymentdetails",
            name="card_holder_city",
        ),
        migrations.RemoveField(
            model_name="stripepaymentdetails",
            name="card_holder_country",
        ),
        migrations.RemoveField(
            model_name="stripepaymentdetails",
            name="card_holder_email",
        ),
        migrations.RemoveField(
            model_name="stripepaymentdetails",
            name="card_holder_name",
        ),
        migrations.RemoveField(
            model_name="stripepaymentdetails",
            name="card_holder_phone",
        ),
        migrations.RemoveField(
            model_name="stripepaymentdetails",
            name="card_holder_state",
        ),
        migrations.RemoveField(
            model_name="stripepaymentdetails",
            name="card_holder_zip",
        ),
        migrations.RemoveField(
            model_name="stripepaymentdetails",
            name="card_number",
        ),
        migrations.RemoveField(
            model_name="stripepaymentdetails",
            name="cvc",
        ),
        migrations.RemoveField(
            model_name="stripepaymentdetails",
            name="expiry_month",
        ),
        migrations.RemoveField(
            model_name="stripepaymentdetails",
            name="expiry_year",
        ),
    ]
