# Generated by Django 4.1.7 on 2023-03-31 01:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stripe", "0005_remove_stripepaymentdetails_card_holder_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stripepaymentdetails",
            name="card_holder_address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="stripepaymentdetails",
            name="card_holder_city",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="stripepaymentdetails",
            name="card_holder_country",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="stripepaymentdetails",
            name="card_holder_email",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="stripepaymentdetails",
            name="card_holder_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="stripepaymentdetails",
            name="card_holder_phone",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="stripepaymentdetails",
            name="card_holder_state",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="stripepaymentdetails",
            name="card_holder_zip",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="stripepaymentdetails",
            name="card_number",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="stripepaymentdetails",
            name="cvc",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="stripepaymentdetails",
            name="expiry_month",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="stripepaymentdetails",
            name="expiry_year",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
