# Generated by Django 4.2.1 on 2023-05-29 01:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stripe", "0006_stripepaymentdetails_card_holder_address_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stripesubscription",
            name="payment_details",
        ),
    ]
