# Generated by Django 4.2.4 on 2023-09-04 21:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("stripe", "0007_remove_stripesubscription_payment_details"),
    ]

    operations = [
        migrations.AddField(
            model_name="stripesubscription",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscription_owner",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
