# Generated by Django 4.2.5 on 2023-10-05 06:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackagePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('type', models.CharField(blank=True, default='subscription', max_length=100, null=True)),
                ('description', models.CharField(default='', max_length=100)),
                ('billing_cycle', models.CharField(default='subscription', max_length=100)),
                ('original_sync_from', models.CharField(blank=True, default='roseware', max_length=100, null=True)),
                ('last_synced_from', models.CharField(blank=True, default='roseware', max_length=100, null=True)),
                ('pipedrive_id', models.CharField(blank=True, max_length=100, null=True)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=100, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customer')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='package_plan_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ServicePackageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('related_app', models.CharField(default='integrations', max_length=100)),
                ('description', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('name', models.CharField(default='', max_length=100)),
                ('type', models.CharField(default='', max_length=100)),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('unit', models.IntegerField(default=1)),
                ('requires_onboarding', models.BooleanField(default=False)),
                ('action', models.CharField(default='create', max_length=100)),
                ('error', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('original_sync_from', models.CharField(blank=True, default='roseware', max_length=100, null=True)),
                ('last_synced_from', models.CharField(blank=True, default='roseware', max_length=100, null=True)),
                ('pipedrive_id', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('stripe_product_id', models.CharField(blank=True, max_length=100, null=True)),
                ('stripe_price_id', models.CharField(blank=True, max_length=100, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='package_template_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ServicePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('related_app', models.CharField(choices=[('Duda', 'Duda'), ('Roseware', 'Roseware'), ('Ayrshare', 'Ayrshare')], default='', max_length=100)),
                ('type', models.CharField(choices=[('Webpage', 'Webpage'), ('Social', 'Social'), ('Blog', 'Blog'), ('Ads', 'Ads')], default='', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('quantity', models.IntegerField(default=1)),
                ('last_completed', models.DateTimeField(blank=True, default=None, max_length=100, null=True)),
                ('date_started', models.DateTimeField(blank=True, default=None, max_length=100, null=True)),
                ('next_scheduled', models.DateTimeField(blank=True, default=None, max_length=100, null=True)),
                ('requires_onboarding', models.BooleanField(default=False)),
                ('action', models.CharField(choices=[('create', 'Create')], default='create', max_length=100)),
                ('error', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('original_sync_from', models.CharField(blank=True, default='roseware', max_length=100, null=True)),
                ('last_synced_from', models.CharField(blank=True, default='roseware', max_length=100, null=True)),
                ('pipedrive_product_attachment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('stripe_subscription_item_id', models.CharField(blank=True, max_length=100, null=True)),
                ('stripe_subscription_item_price_id', models.CharField(blank=True, max_length=100, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customer')),
                ('package_plan', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='package_manager.packageplan')),
                ('package_template', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='package_manager.servicepackagetemplate')),
            ],
        ),
    ]
