# Generated by Django 4.1.7 on 2023-02-17 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(default='')),
                ('cost', models.TextField(default='')),
                ('customer', models.TextField(default='')),
                ('is_active', models.TextField(default='')),
                ('last_completed', models.TextField(default='')),
                ('date_started', models.TextField(default='')),
                ('next_scheduled', models.TextField(default='')),
                ('action', models.TextField(default='')),
                ('error', models.TextField(default='')),
            ],
        ),
    ]
