# Generated by Django 4.1.7 on 2023-02-25 02:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("package_manager", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicepackage",
            name="related_app",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="servicepackage",
            name="date_started",
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name="servicepackage",
            name="last_completed",
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name="servicepackage",
            name="next_scheduled",
            field=models.DateField(default=None),
        ),
    ]
