# Generated by Django 4.1.7 on 2023-02-26 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_rename_start_date_customer_onboarding_date_and_more"),
        ("package_manager", "0002_servicepackage_related_app_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicepackage",
            name="action",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="servicepackage",
            name="cost",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="servicepackage",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="accounts.customer"
            ),
        ),
        migrations.AlterField(
            model_name="servicepackage",
            name="date_started",
            field=models.DateField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name="servicepackage",
            name="error",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="servicepackage",
            name="is_active",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="servicepackage",
            name="last_completed",
            field=models.DateField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name="servicepackage",
            name="next_scheduled",
            field=models.DateField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name="servicepackage",
            name="related_app",
            field=models.CharField(
                choices=[
                    ("duda", "Duda"),
                    ("custom", "Custom"),
                    ("ayrshare", "Ayrshare"),
                ],
                default="",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="servicepackage",
            name="type",
            field=models.CharField(
                choices=[("web", "Web"), ("social", "Social"), ("blog", "Blog")],
                default="",
                max_length=100,
            ),
        ),
    ]
