# Generated by Django 4.1.7 on 2023-02-27 04:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("package_manager", "0004_alter_servicepackage_cost_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicepackage",
            name="action",
            field=models.CharField(
                choices=[("create", "Create")], default="create", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="servicepackage",
            name="date_started",
            field=models.DateTimeField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name="servicepackage",
            name="last_completed",
            field=models.DateTimeField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name="servicepackage",
            name="next_scheduled",
            field=models.DateTimeField(default=None, max_length=100),
        ),
    ]
