# Generated by Django 4.1.7 on 2023-03-04 19:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("package_manager", "0005_alter_servicepackage_action_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicepackage",
            name="related_app",
            field=models.CharField(
                choices=[
                    ("duda", "Duda"),
                    ("markit", "Markit"),
                    ("ayrshare", "Ayrshare"),
                ],
                default="",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="servicepackage",
            name="type",
            field=models.CharField(
                choices=[
                    ("web", "Web"),
                    ("social", "Social"),
                    ("blog", "Blog"),
                    ("ads", "Ads"),
                ],
                default="",
                max_length=100,
            ),
        ),
    ]
