# Generated by Django 4.1.7 on 2023-03-04 19:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("package_manager", "0006_alter_servicepackage_related_app_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicepackage",
            name="type",
            field=models.CharField(
                choices=[
                    ("webpage", "Webpage"),
                    ("social", "Social"),
                    ("blog", "Blog"),
                    ("ads", "Ads"),
                ],
                default="",
                max_length=100,
            ),
        ),
    ]
