# Generated by Django 4.1.7 on 2023-03-08 05:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("package_manager", "0007_alter_servicepackage_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicepackage",
            name="requires_onboarding",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="servicepackage",
            name="next_scheduled",
            field=models.DateTimeField(blank=True, max_length=100, null=True),
        ),
    ]
