# Generated by Django 4.1.7 on 2023-03-12 04:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("package_manager", "0009_alter_servicepackage_last_completed_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicepackage",
            name="date_started",
            field=models.DateTimeField(
                blank=True, default=None, max_length=100, null=True
            ),
        ),
    ]
