# Generated by Django 4.1.7 on 2023-03-23 01:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("package_manager", "0010_alter_servicepackage_date_started"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServicePackageTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "related_app",
                    models.CharField(
                        choices=[
                            ("duda", "Duda"),
                            ("markit", "Markit"),
                            ("ayrshare", "Ayrshare"),
                        ],
                        default="",
                        max_length=100,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("webpage", "Webpage"),
                            ("social", "Social"),
                            ("blog", "Blog"),
                            ("ads", "Ads"),
                        ],
                        default="",
                        max_length=100,
                    ),
                ),
                ("cost", models.DecimalField(decimal_places=2, max_digits=6)),
                ("requires_onboarding", models.BooleanField(default=False)),
                (
                    "action",
                    models.CharField(
                        choices=[("create", "Create")], default="create", max_length=100
                    ),
                ),
                ("error", models.CharField(default="", max_length=100)),
            ],
        ),
    ]
