# Generated by Django 4.1.7 on 2023-03-23 02:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("package_manager", "0012_alter_servicepackagetemplate_error"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicepackagetemplate",
            name="pipedrive_product_code",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
