# Generated by Django 4.1.7 on 2023-03-23 02:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("package_manager", "0014_servicepackagetemplate_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="servicepackagetemplate",
            old_name="pipedrive_product_code",
            new_name="pipedrive_id",
        ),
    ]
