# Generated by Django 4.1.7 on 2023-03-25 02:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("package_manager", "0016_servicepackage_package_template"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicepackage",
            name="cost",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=6, null=True
            ),
        ),
    ]
