# Generated by Django 4.1.7 on 2023-03-25 02:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("package_manager", "0017_alter_servicepackage_cost"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicepackage",
            name="cost",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name="servicepackagetemplate",
            name="cost",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
