# Generated by Django 4.1.7 on 2023-03-25 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0009_customer_pipedrive_id"),
        ("package_manager", "0018_alter_servicepackage_cost_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicepackage",
            name="package_template",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="package_manager.servicepackagetemplate",
            ),
        ),
        migrations.CreateModel(
            name="PackagePlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=100)),
                ("status", models.CharField(default="open", max_length=100)),
                ("description", models.CharField(default="", max_length=100)),
                ("billing_cycle", models.CharField(default="monthly", max_length=100)),
                (
                    "pipedrive_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "customer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.customer",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="servicepackage",
            name="package_plan",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="package_manager.packageplan",
            ),
        ),
    ]
