# Generated by Django 4.1.7 on 2023-03-25 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0009_customer_pipedrive_id"),
        (
            "package_manager",
            "0019_alter_servicepackage_package_template_packageplan_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="packageplan",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="accounts.customer"
            ),
        ),
    ]
