# Generated by Django 4.1.7 on 2023-03-26 21:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("package_manager", "0020_alter_packageplan_customer"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicepackage",
            name="pipedrive_product_attachment_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
