# Generated by Django 4.1.7 on 2023-03-29 02:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("package_manager", "0022_alter_servicepackage_error"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicepackagetemplate",
            name="stripe_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
