# Generated by Django 4.1.7 on 2023-03-29 04:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("package_manager", "0023_servicepackagetemplate_stripe_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="servicepackagetemplate",
            old_name="stripe_id",
            new_name="stripe_price_id",
        ),
        migrations.AddField(
            model_name="servicepackagetemplate",
            name="stripe_product_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
