# Generated by Django 4.1.7 on 2023-04-01 00:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "package_manager",
            "0024_rename_stripe_id_servicepackagetemplate_stripe_price_id_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="servicepackage",
            name="stripe_subscription_item_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
