# Generated by Django 4.1.7 on 2023-04-01 00:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("package_manager", "0025_servicepackage_stripe_subscription_item_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicepackage",
            name="quantity",
            field=models.IntegerField(default=1),
        ),
    ]
