# Generated by Django 4.1.7 on 2023-04-01 19:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("package_manager", "0027_alter_servicepackage_related_app_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicepackage",
            name="stripe_subscription_item_price_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
