# Generated by Django 4.1.7 on 2023-04-01 22:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("package_manager", "0028_servicepackage_stripe_subscription_item_price_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="packageplan",
            name="stripe_subscription_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
