# Generated by Django 4.2 on 2023-04-05 03:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("package_manager", "0030_alter_servicepackage_action_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="packageplan",
            name="billing_cycle",
            field=models.CharField(default="subscription", max_length=100),
        ),
        migrations.AlterField(
            model_name="servicepackage",
            name="action",
            field=models.CharField(
                choices=[("create", "Create")], default="create", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="servicepackage",
            name="related_app",
            field=models.CharField(
                choices=[
                    ("Duda", "Duda"),
                    ("Markit", "Markit"),
                    ("Ayrshare", "Ayrshare"),
                ],
                default="",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="servicepackage",
            name="type",
            field=models.CharField(
                choices=[
                    ("Webpage", "Webpage"),
                    ("Social", "Social"),
                    ("Blog", "Blog"),
                    ("Ads", "Ads"),
                ],
                default="",
                max_length=100,
            ),
        ),
    ]
