# Generated by Django 4.2 on 2023-04-08 22:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("package_manager", "0031_alter_packageplan_billing_cycle_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicepackagetemplate",
            name="description",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
    ]
