# Generated by Django 4.2 on 2023-04-11 01:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("package_manager", "0034_servicepackagetemplate_last_synced_from"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicepackagetemplate",
            name="description",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
    ]
