# Generated by Django 4.2 on 2023-04-12 00:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("package_manager", "0036_servicepackagetemplate_original_sync_from"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicepackagetemplate",
            name="pipedrive_id",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
    ]
