# Generated by Django 4.2 on 2023-04-16 06:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "package_manager",
            "0038_alter_servicepackagetemplate_last_synced_from_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="packageplan",
            name="type",
            field=models.CharField(default="subscription", max_length=100),
        ),
    ]
