# Generated by Django 4.2 on 2023-04-16 06:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("package_manager", "0039_packageplan_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="packageplan",
            name="last_synced_from",
            field=models.CharField(
                blank=True, default="roseware", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="packageplan",
            name="original_sync_from",
            field=models.CharField(
                blank=True, default="roseware", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="servicepackage",
            name="last_synced_from",
            field=models.CharField(
                blank=True, default="roseware", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="servicepackage",
            name="original_sync_from",
            field=models.CharField(
                blank=True, default="roseware", max_length=100, null=True
            ),
        ),
    ]
