# Generated by Django 4.2.1 on 2023-05-10 03:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("package_manager", "0040_packageplan_last_synced_from_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicepackagetemplate",
            name="action",
            field=models.CharField(default="create", max_length=100),
        ),
        migrations.AlterField(
            model_name="servicepackagetemplate",
            name="related_app",
            field=models.CharField(default="integrations", max_length=100),
        ),
    ]
