# Generated by Django 4.2.1 on 2023-05-28 20:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("package_manager", "0041_alter_servicepackagetemplate_action_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicepackagetemplate",
            name="unit",
            field=models.IntegerField(default=1),
        ),
    ]
