# Generated by Django 4.2.1 on 2023-05-28 23:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("package_manager", "0042_servicepackagetemplate_unit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="packageplan",
            name="type",
            field=models.CharField(
                blank=True, default="subscription", max_length=100, null=True
            ),
        ),
    ]
