# Generated by Django 4.2.1 on 2023-05-28 23:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("package_manager", "0043_alter_packageplan_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="packageplan",
            name="status",
            field=models.CharField(max_length=100),
        ),
    ]
