# Generated by Django 4.2.1 on 2023-06-24 03:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("package_manager", "0044_alter_packageplan_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicepackage",
            name="related_app",
            field=models.CharField(
                choices=[
                    ("Duda", "Duda"),
                    ("Roseware", "Roseware"),
                    ("Ayrshare", "Ayrshare"),
                ],
                default="",
                max_length=100,
            ),
        ),
    ]
