# Generated by Django 4.2.5 on 2023-10-04 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_customuser_alter_customer_owner_alter_customer_user_and_more'),
        ('package_manager', '0047_alter_servicepackage_package_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packageplan',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='package_plan_owner', to='accounts.customuser'),
        ),
        migrations.AlterField(
            model_name='servicepackagetemplate',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='package_template_owner', to='accounts.customuser'),
        ),
    ]
